### PR TITLE
Implement x86 simd rounding instructions

### PR DESCRIPTION
**Pull request by kulcsaradam**
Implement f32x4 and f64x2 ceil, floor, trunc, nearest.

### CODE REVIEW

**Comment by kulcsaradam** [comment]
Rebased the patch to main branch.

**Review by zherczeg — APPROVED** [review]
LGTM

**Comment by zherczeg** [comment]
Since the code is in the main branch now, I cannot land the patch alone anymore.

**Comment by zherczeg** [comment]
Could you rebase the patch? That should enable ci testing.

**Review by zherczeg — APPROVED** [review]
Still LGTM

**Review by clover2123 — APPROVED** [review]
LGTM

**Pull request merged**
