### PR TITLE
Add matrix multiplication benchmark

### PR DESCRIPTION
**Pull request by taperropein**
Hi!  This is my first PR, so I hope I'm doing it correctly.

I started adding SIMD benchmarks from [this WASM SIMD repo](https://github.com/ngzhian/simd-benchmarks/).

The first is a double precision matrix multiplication benchmark, which covers these previously not benchmarked instructions:
```
f64x2.add
f64x2.mul
v128.load64_splat
```

I also have a tiny bash script for listing which instructions are covered in the benchmarks, let me know if I should include that in the PR as well.

### CODE REVIEW

**Comment by zherczeg** [comment]
NIce! Would be good to split it into two benchmarks, buecasue this way the performance of simd an non-simd variant cannot be compared

**Comment by taperropein** [comment]
Hmm, then the result will need to be checked differently.  I'll try using a CRC32 checksum, since that's quick to calculate and doesn't add much code.

**Comment by zherczeg** [comment]
A simple sum could be enough

**Comment by taperropein** [comment]
That should do it.

**Review by ksh8281 — APPROVED** [review]
Nice job!

**Pull request merged**
