### PR TITLE
move wabt files into third_party

### PR DESCRIPTION
**Pull request by ksh8281**
Signed-off-by: Seonghyun Kim <sh8281.kim@samsung.com>

### CODE REVIEW

**Comment by zherczeg** [comment]
All files are moved to third party, am I right? How would this affect the jit compiler? Shall it go there as well?

**Comment by ksh8281** [comment]
IMO our implementation should be located on /src/ folder

**Comment by zherczeg** [comment]
Ok. Shall we make an independent interface to use jit? Currently it is used through the webassembly interpreter, so some modifications in the thrid_party is needed.

**Comment by ksh8281** [comment]
Yes. You can write independent interface.
We will make new interpreter and runtime for better performance and memory management by bdwgc

**Review by clover2123 — APPROVED** [review]
LGTM

**Comment by clover2123** [comment]
@zherczeg 
Is there other issue that we should discuss now?

**Comment by zherczeg** [comment]
No. Please land the patch. I will do the merge.

**Pull request merged**
