### PR TITLE
Rework exception setting in JIT

### PR DESCRIPTION
**Pull request by zherczeg**
Follows #220

### CODE REVIEW

**Comment by zherczeg** [comment]
The new approach does not require to reserve a register for exception handling.
Also it does not generate handlers when they are not needed.

**Comment by zherczeg** [comment]
The patch is completely reworked to create trap handlers at the end of a function. This significantly simplified the patch. The recent branch optimizations in the jit compiler should make this approach good. The patch is ready for review.

**Comment by zherczeg** [comment]
Patch is reworked to use the constants.

**Review by clover2123 — APPROVED** [review]
LGTM

**Pull request merged**
