### PR TITLE
Reduce stack usage of jit

### PR DESCRIPTION
**Pull request by zherczeg**

### CODE REVIEW

**Comment by zherczeg** [comment]
This patch removes some old codes, and also reduce the temporary stack usage.

**Comment by zherczeg** [comment]
This patch affects #285, whichever goes first, the other needs to be updated.

**Comment by clover2123** [comment]
Does this patch need more updates?

**Comment by zherczeg** [comment]
I have updated the patch. Thank you

**Review by clover2123 — APPROVED** [review]
LGTM

**Pull request merged**
