### PR TITLE
Memory stack

### PR DESCRIPTION
**Pull request by zherczeg**
This is not the only option to do this. If we could store the instance in a register (my long term plan), we could cache the memory in the instance. Then saving/restoring would be unnecessary.

### CODE REVIEW

**Comment by zherczeg** [comment]
Patch is ready for review

**Comment by clover2123** [comment]
Although this patch is not relevant to it, but I wonder that if we are going to support [multiple memories](https://github.com/WebAssembly/multi-memory/blob/main/proposals/multi-memory/Overview.md) this caching strategy would be valid or easily updated for it?

**Comment by zherczeg** [comment]
To tell you the truth, I plan to rework this whole caching after #289, where I will remove most of these changes. However, I cannot do that in one step. The caching should be done by the Instance after that point. This will work well for multi memory, and the caching overhead will be smaller. Using the instance pointer, I can directly access the cache.

**Review by clover2123 — APPROVED** [review]
LGTM

**Pull request merged**
