### PR TITLE
Implement relaxed simd in the interpreter

### PR DESCRIPTION
**Pull request by zherczeg**
Contains #291, that should land first.

### CODE REVIEW

**Comment by zherczeg** [comment]
I have updated this patch.

**Review by clover2123 — APPROVED** [review]
LGTM

**Comment by clover2123** [comment]
BTW did you get test cases from https://github.com/WebAssembly/relaxed-simd?

**Comment by zherczeg** [comment]
Yes! These are the tests: https://github.com/WebAssembly/relaxed-simd/tree/main/test/core/relaxed-simd

**Comment by clover2123** [comment]
@zherczeg Thanks for the quick update!

**Pull request merged**
